services:

  apache-php:
    build: .
    container_name: mi_apache
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - ./tiendaropa.sql:/docker-entrypoint-initdb.d/tiendaropa.sql
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mi_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
